#! /usr/bin/env bash
# check if ~/.bashrc does not exist
if [ ! -f ~/.bashrc ]; then
    echo "Copy config from /etc/skel to ~/"
    cp -r /etc/skel/. ~/

    echo "source /opt/ros/humble/setup.bash" >>~/.bashrc

    
fi
