/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) param_func_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 4, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};

/* param_func:(Head[4x4],LeftHand[4x4],RightHand[4x4])->(left_hand_pos[3],right_hand_pos[3],head_pos[3],head_front_dir[3],head_up_dir[3],left_hand_front_dir[3],left_hand_outside_dir[3],right_hand_front_dir[3],right_hand_outside_dir[3],torso_dir[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[2]? arg[2][12] : 0;
  if (res[1]!=0) res[1][0]=a0;
  a0=arg[2]? arg[2][13] : 0;
  if (res[1]!=0) res[1][1]=a0;
  a0=arg[2]? arg[2][14] : 0;
  if (res[1]!=0) res[1][2]=a0;
  a0=arg[0]? arg[0][12] : 0;
  if (res[2]!=0) res[2][0]=a0;
  a1=arg[0]? arg[0][13] : 0;
  if (res[2]!=0) res[2][1]=a1;
  a2=arg[0]? arg[0][14] : 0;
  if (res[2]!=0) res[2][2]=a2;
  a3=arg[0]? arg[0][0] : 0;
  if (res[3]!=0) res[3][0]=a3;
  a3=arg[0]? arg[0][1] : 0;
  if (res[3]!=0) res[3][1]=a3;
  a3=arg[0]? arg[0][2] : 0;
  if (res[3]!=0) res[3][2]=a3;
  a3=arg[0]? arg[0][8] : 0;
  if (res[4]!=0) res[4][0]=a3;
  a3=arg[0]? arg[0][9] : 0;
  if (res[4]!=0) res[4][1]=a3;
  a3=arg[0]? arg[0][10] : 0;
  if (res[4]!=0) res[4][2]=a3;
  a3=arg[1]? arg[1][0] : 0;
  if (res[5]!=0) res[5][0]=a3;
  a3=arg[1]? arg[1][1] : 0;
  if (res[5]!=0) res[5][1]=a3;
  a3=arg[1]? arg[1][2] : 0;
  if (res[5]!=0) res[5][2]=a3;
  a3=arg[1]? arg[1][8] : 0;
  a3=(-a3);
  if (res[6]!=0) res[6][0]=a3;
  a3=arg[1]? arg[1][9] : 0;
  a3=(-a3);
  if (res[6]!=0) res[6][1]=a3;
  a3=arg[1]? arg[1][10] : 0;
  a3=(-a3);
  if (res[6]!=0) res[6][2]=a3;
  a3=arg[2]? arg[2][0] : 0;
  if (res[7]!=0) res[7][0]=a3;
  a3=arg[2]? arg[2][1] : 0;
  if (res[7]!=0) res[7][1]=a3;
  a3=arg[2]? arg[2][2] : 0;
  if (res[7]!=0) res[7][2]=a3;
  a3=arg[2]? arg[2][8] : 0;
  a3=(-a3);
  if (res[8]!=0) res[8][0]=a3;
  a3=arg[2]? arg[2][9] : 0;
  a3=(-a3);
  if (res[8]!=0) res[8][1]=a3;
  a3=arg[2]? arg[2][10] : 0;
  a3=(-a3);
  if (res[8]!=0) res[8][2]=a3;
  a3=casadi_sq(a0);
  a4=casadi_sq(a1);
  a3=(a3+a4);
  a4=casadi_sq(a2);
  a3=(a3+a4);
  a3=sqrt(a3);
  a0=(a0/a3);
  if (res[9]!=0) res[9][0]=a0;
  a1=(a1/a3);
  if (res[9]!=0) res[9][1]=a1;
  a2=(a2/a3);
  if (res[9]!=0) res[9][2]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int param_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int param_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int param_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void param_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int param_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void param_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void param_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void param_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int param_func_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int param_func_n_out(void) { return 10;}

CASADI_SYMBOL_EXPORT casadi_real param_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* param_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "Head";
    case 1: return "LeftHand";
    case 2: return "RightHand";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* param_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "left_hand_pos";
    case 1: return "right_hand_pos";
    case 2: return "head_pos";
    case 3: return "head_front_dir";
    case 4: return "head_up_dir";
    case 5: return "left_hand_front_dir";
    case 6: return "left_hand_outside_dir";
    case 7: return "right_hand_front_dir";
    case 8: return "right_hand_outside_dir";
    case 9: return "torso_dir";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* param_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* param_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s1;
    case 6: return casadi_s1;
    case 7: return casadi_s1;
    case 8: return casadi_s1;
    case 9: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int param_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int param_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 10*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
