/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) param_func_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 4, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};

/* param_func:(BodyHips[4x4],BodySpineUpper[4x4],BodyLeftScapula[4x4],BodyRightScapula[4x4],BodyHead[4x4],BodyLeftHandMiddleMetacarpal[4x4],BodyLeftHandIndexTip[4x4],BodyLeftHandMiddleTip[4x4],BodyLeftHandRingTip[4x4],BodyLeftHandLittleTip[4x4],BodyLeftHandThumbTip[4x4],BodyRightHandMiddleMetacarpal[4x4],BodyRightHandIndexTip[4x4],BodyRightHandMiddleTip[4x4],BodyRightHandRingTip[4x4],BodyRightHandLittleTip[4x4],BodyRightHandThumbTip[4x4],BodyLeftArmUpper[4x4],BodyRightArmUpper[4x4],BodyLeftArmLower[4x4],BodyRightArmLower[4x4],BodyLeftHandMiddleProximal[4x4],BodyRightHandMiddleProximal[4x4],BodyLeftUpperLeg[4x4],BodyLeftLowerLeg[4x4],BodyLeftFootAnkleTwist[4x4],BodyRightUpperLeg[4x4],BodyRightLowerLeg[4x4],BodyRightFootAnkleTwist[4x4],BodyLeftFootSubtalar[4x4],BodyLeftFootBall[4x4],BodyRightFootSubtalar[4x4],BodyRightFootBall[4x4])->(root_dir_z[3],root_dir_y[3],root_pos[3],torso_dir[3],shoulder_dir[3],head_front_dir[3],head_up_dir[3],L_upper_arm_dir[3],L_lower_arm_dir[3],R_upper_arm_dir[3],R_lower_arm_dir[3],L_upper_leg_dir[3],L_lower_leg_dir[3],R_upper_leg_dir[3],R_lower_leg_dir[3],L_foot_dir_front[3],R_foot_dir_front[3],L_hand_dir_front[3],L_hand_dir_outside[3],R_hand_dir_front[3],R_hand_dir_outside[3],PosInHand_BodyRightHandThumbTip[3],PosInHand_BodyRightHandIndexTip[3],PosInHand_BodyRightHandMiddleTip[3],PosInHand_BodyRightHandRingTip[3],PosInHand_BodyRightHandLittleTip[3],PosInHand_BodyLeftHandThumbTip[3],PosInHand_BodyLeftHandIndexTip[3],PosInHand_BodyLeftHandMiddleTip[3],PosInHand_BodyLeftHandRingTip[3],PosInHand_BodyLeftHandLittleTip[3],DirInHand_BodyRightHandThumbTip[3],DirInHand_BodyRightHandIndexTip[3],DirInHand_BodyRightHandMiddleTip[3],DirInHand_BodyRightHandRingTip[3],DirInHand_BodyRightHandLittleTip[3],DirInHand_BodyLeftHandThumbTip[3],DirInHand_BodyLeftHandIndexTip[3],DirInHand_BodyLeftHandMiddleTip[3],DirInHand_BodyLeftHandRingTip[3],DirInHand_BodyLeftHandLittleTip[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29;
  a00=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][0] : 0;
  a00=(-a00);
  if (res[1]!=0) res[1][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a00=(-a00);
  if (res[1]!=0) res[1][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  a00=(-a00);
  if (res[1]!=0) res[1][2]=a00;
  a00=arg[0]? arg[0][12] : 0;
  if (res[2]!=0) res[2][0]=a00;
  a00=arg[0]? arg[0][13] : 0;
  if (res[2]!=0) res[2][1]=a00;
  a00=arg[0]? arg[0][14] : 0;
  if (res[2]!=0) res[2][2]=a00;
  a00=arg[1]? arg[1][4] : 0;
  if (res[3]!=0) res[3][0]=a00;
  a00=arg[1]? arg[1][5] : 0;
  if (res[3]!=0) res[3][1]=a00;
  a00=arg[1]? arg[1][6] : 0;
  if (res[3]!=0) res[3][2]=a00;
  a00=arg[3]? arg[3][12] : 0;
  a01=arg[2]? arg[2][12] : 0;
  a00=(a00-a01);
  a01=casadi_sq(a00);
  a02=arg[3]? arg[3][13] : 0;
  a03=arg[2]? arg[2][13] : 0;
  a02=(a02-a03);
  a03=casadi_sq(a02);
  a01=(a01+a03);
  a03=arg[3]? arg[3][14] : 0;
  a04=arg[2]? arg[2][14] : 0;
  a03=(a03-a04);
  a04=casadi_sq(a03);
  a01=(a01+a04);
  a01=sqrt(a01);
  a00=(a00/a01);
  if (res[4]!=0) res[4][0]=a00;
  a02=(a02/a01);
  if (res[4]!=0) res[4][1]=a02;
  a03=(a03/a01);
  if (res[4]!=0) res[4][2]=a03;
  a03=arg[4]? arg[4][8] : 0;
  if (res[5]!=0) res[5][0]=a03;
  a03=arg[4]? arg[4][9] : 0;
  if (res[5]!=0) res[5][1]=a03;
  a03=arg[4]? arg[4][10] : 0;
  if (res[5]!=0) res[5][2]=a03;
  a03=arg[4]? arg[4][4] : 0;
  if (res[6]!=0) res[6][0]=a03;
  a03=arg[4]? arg[4][5] : 0;
  if (res[6]!=0) res[6][1]=a03;
  a03=arg[4]? arg[4][6] : 0;
  if (res[6]!=0) res[6][2]=a03;
  a03=arg[17]? arg[17][4] : 0;
  if (res[7]!=0) res[7][0]=a03;
  a03=arg[17]? arg[17][5] : 0;
  if (res[7]!=0) res[7][1]=a03;
  a03=arg[17]? arg[17][6] : 0;
  if (res[7]!=0) res[7][2]=a03;
  a03=arg[19]? arg[19][4] : 0;
  if (res[8]!=0) res[8][0]=a03;
  a03=arg[19]? arg[19][5] : 0;
  if (res[8]!=0) res[8][1]=a03;
  a03=arg[19]? arg[19][6] : 0;
  if (res[8]!=0) res[8][2]=a03;
  a03=arg[18]? arg[18][4] : 0;
  a03=(-a03);
  if (res[9]!=0) res[9][0]=a03;
  a03=arg[18]? arg[18][5] : 0;
  a03=(-a03);
  if (res[9]!=0) res[9][1]=a03;
  a03=arg[18]? arg[18][6] : 0;
  a03=(-a03);
  if (res[9]!=0) res[9][2]=a03;
  a03=arg[20]? arg[20][4] : 0;
  a03=(-a03);
  if (res[10]!=0) res[10][0]=a03;
  a03=arg[20]? arg[20][5] : 0;
  a03=(-a03);
  if (res[10]!=0) res[10][1]=a03;
  a03=arg[20]? arg[20][6] : 0;
  a03=(-a03);
  if (res[10]!=0) res[10][2]=a03;
  a03=arg[24]? arg[24][12] : 0;
  a01=arg[23]? arg[23][12] : 0;
  a01=(a03-a01);
  a02=casadi_sq(a01);
  a00=arg[24]? arg[24][13] : 0;
  a04=arg[23]? arg[23][13] : 0;
  a04=(a00-a04);
  a05=casadi_sq(a04);
  a02=(a02+a05);
  a05=arg[24]? arg[24][14] : 0;
  a06=arg[23]? arg[23][14] : 0;
  a06=(a05-a06);
  a07=casadi_sq(a06);
  a02=(a02+a07);
  a02=sqrt(a02);
  a01=(a01/a02);
  if (res[11]!=0) res[11][0]=a01;
  a04=(a04/a02);
  if (res[11]!=0) res[11][1]=a04;
  a06=(a06/a02);
  if (res[11]!=0) res[11][2]=a06;
  a06=arg[25]? arg[25][12] : 0;
  a06=(a06-a03);
  a03=casadi_sq(a06);
  a02=arg[25]? arg[25][13] : 0;
  a02=(a02-a00);
  a00=casadi_sq(a02);
  a03=(a03+a00);
  a00=arg[25]? arg[25][14] : 0;
  a00=(a00-a05);
  a05=casadi_sq(a00);
  a03=(a03+a05);
  a03=sqrt(a03);
  a06=(a06/a03);
  if (res[12]!=0) res[12][0]=a06;
  a02=(a02/a03);
  if (res[12]!=0) res[12][1]=a02;
  a00=(a00/a03);
  if (res[12]!=0) res[12][2]=a00;
  a00=arg[27]? arg[27][12] : 0;
  a03=arg[26]? arg[26][12] : 0;
  a03=(a00-a03);
  a02=casadi_sq(a03);
  a06=arg[27]? arg[27][13] : 0;
  a05=arg[26]? arg[26][13] : 0;
  a05=(a06-a05);
  a04=casadi_sq(a05);
  a02=(a02+a04);
  a04=arg[27]? arg[27][14] : 0;
  a01=arg[26]? arg[26][14] : 0;
  a01=(a04-a01);
  a07=casadi_sq(a01);
  a02=(a02+a07);
  a02=sqrt(a02);
  a03=(a03/a02);
  if (res[13]!=0) res[13][0]=a03;
  a05=(a05/a02);
  if (res[13]!=0) res[13][1]=a05;
  a01=(a01/a02);
  if (res[13]!=0) res[13][2]=a01;
  a01=arg[28]? arg[28][12] : 0;
  a01=(a01-a00);
  a00=casadi_sq(a01);
  a02=arg[28]? arg[28][13] : 0;
  a02=(a02-a06);
  a06=casadi_sq(a02);
  a00=(a00+a06);
  a06=arg[28]? arg[28][14] : 0;
  a06=(a06-a04);
  a04=casadi_sq(a06);
  a00=(a00+a04);
  a00=sqrt(a00);
  a01=(a01/a00);
  if (res[14]!=0) res[14][0]=a01;
  a02=(a02/a00);
  if (res[14]!=0) res[14][1]=a02;
  a06=(a06/a00);
  if (res[14]!=0) res[14][2]=a06;
  a06=arg[30]? arg[30][12] : 0;
  a00=arg[29]? arg[29][12] : 0;
  a06=(a06-a00);
  a00=casadi_sq(a06);
  a02=arg[30]? arg[30][13] : 0;
  a01=arg[29]? arg[29][13] : 0;
  a02=(a02-a01);
  a01=casadi_sq(a02);
  a00=(a00+a01);
  a01=arg[30]? arg[30][14] : 0;
  a04=arg[29]? arg[29][14] : 0;
  a01=(a01-a04);
  a04=casadi_sq(a01);
  a00=(a00+a04);
  a00=sqrt(a00);
  a06=(a06/a00);
  if (res[15]!=0) res[15][0]=a06;
  a02=(a02/a00);
  if (res[15]!=0) res[15][1]=a02;
  a01=(a01/a00);
  if (res[15]!=0) res[15][2]=a01;
  a01=arg[32]? arg[32][12] : 0;
  a00=arg[31]? arg[31][12] : 0;
  a01=(a01-a00);
  a00=casadi_sq(a01);
  a02=arg[32]? arg[32][13] : 0;
  a06=arg[31]? arg[31][13] : 0;
  a02=(a02-a06);
  a06=casadi_sq(a02);
  a00=(a00+a06);
  a06=arg[32]? arg[32][14] : 0;
  a04=arg[31]? arg[31][14] : 0;
  a06=(a06-a04);
  a04=casadi_sq(a06);
  a00=(a00+a04);
  a00=sqrt(a00);
  a01=(a01/a00);
  if (res[16]!=0) res[16][0]=a01;
  a02=(a02/a00);
  if (res[16]!=0) res[16][1]=a02;
  a06=(a06/a00);
  if (res[16]!=0) res[16][2]=a06;
  a06=arg[5]? arg[5][4] : 0;
  if (res[17]!=0) res[17][0]=a06;
  a00=arg[5]? arg[5][5] : 0;
  if (res[17]!=0) res[17][1]=a00;
  a02=arg[5]? arg[5][6] : 0;
  if (res[17]!=0) res[17][2]=a02;
  a01=arg[21]? arg[21][0] : 0;
  if (res[18]!=0) res[18][0]=a01;
  a01=arg[21]? arg[21][1] : 0;
  if (res[18]!=0) res[18][1]=a01;
  a01=arg[21]? arg[21][2] : 0;
  if (res[18]!=0) res[18][2]=a01;
  a01=arg[11]? arg[11][4] : 0;
  a04=(-a01);
  if (res[19]!=0) res[19][0]=a04;
  a04=arg[11]? arg[11][5] : 0;
  a05=(-a04);
  if (res[19]!=0) res[19][1]=a05;
  a05=arg[11]? arg[11][6] : 0;
  a03=(-a05);
  if (res[19]!=0) res[19][2]=a03;
  a03=arg[22]? arg[22][0] : 0;
  a03=(-a03);
  if (res[20]!=0) res[20][0]=a03;
  a03=arg[22]? arg[22][1] : 0;
  a03=(-a03);
  if (res[20]!=0) res[20][1]=a03;
  a03=arg[22]? arg[22][2] : 0;
  a03=(-a03);
  if (res[20]!=0) res[20][2]=a03;
  a03=8.0000000000000004e-01;
  a07=arg[11]? arg[11][0] : 0;
  a08=arg[16]? arg[16][12] : 0;
  a09=arg[11]? arg[11][12] : 0;
  a08=(a08-a09);
  a10=(a07*a08);
  a11=arg[11]? arg[11][1] : 0;
  a12=arg[16]? arg[16][13] : 0;
  a13=arg[11]? arg[11][13] : 0;
  a12=(a12-a13);
  a14=(a11*a12);
  a15=arg[11]? arg[11][2] : 0;
  a16=arg[16]? arg[16][14] : 0;
  a17=arg[11]? arg[11][14] : 0;
  a16=(a16-a17);
  a18=(a15*a16);
  a14=(a14+a18);
  a10=(a10+a14);
  a10=(a03*a10);
  if (res[21]!=0) res[21][0]=a10;
  a10=1.3000000000000000e+00;
  a14=(a01*a08);
  a18=(a04*a12);
  a19=(a05*a16);
  a18=(a18+a19);
  a14=(a14+a18);
  a14=(a10*a14);
  if (res[21]!=0) res[21][1]=a14;
  a14=1.2000000000000000e+00;
  a18=arg[11]? arg[11][8] : 0;
  a08=(a18*a08);
  a19=arg[11]? arg[11][9] : 0;
  a12=(a19*a12);
  a20=arg[11]? arg[11][10] : 0;
  a16=(a20*a16);
  a12=(a12+a16);
  a08=(a08+a12);
  a08=(a14*a08);
  if (res[21]!=0) res[21][2]=a08;
  a08=arg[12]? arg[12][12] : 0;
  a08=(a08-a09);
  a12=(a07*a08);
  a16=arg[12]? arg[12][13] : 0;
  a16=(a16-a13);
  a21=(a11*a16);
  a22=arg[12]? arg[12][14] : 0;
  a22=(a22-a17);
  a23=(a15*a22);
  a21=(a21+a23);
  a12=(a12+a21);
  a12=(a03*a12);
  if (res[22]!=0) res[22][0]=a12;
  a12=(a01*a08);
  a21=(a04*a16);
  a23=(a05*a22);
  a21=(a21+a23);
  a12=(a12+a21);
  a12=(a10*a12);
  if (res[22]!=0) res[22][1]=a12;
  a08=(a18*a08);
  a16=(a19*a16);
  a22=(a20*a22);
  a16=(a16+a22);
  a08=(a08+a16);
  a08=(a14*a08);
  if (res[22]!=0) res[22][2]=a08;
  a08=arg[13]? arg[13][12] : 0;
  a08=(a08-a09);
  a16=(a07*a08);
  a22=arg[13]? arg[13][13] : 0;
  a22=(a22-a13);
  a12=(a11*a22);
  a21=arg[13]? arg[13][14] : 0;
  a21=(a21-a17);
  a23=(a15*a21);
  a12=(a12+a23);
  a16=(a16+a12);
  a16=(a03*a16);
  if (res[23]!=0) res[23][0]=a16;
  a16=(a01*a08);
  a12=(a04*a22);
  a23=(a05*a21);
  a12=(a12+a23);
  a16=(a16+a12);
  a16=(a10*a16);
  if (res[23]!=0) res[23][1]=a16;
  a08=(a18*a08);
  a22=(a19*a22);
  a21=(a20*a21);
  a22=(a22+a21);
  a08=(a08+a22);
  a08=(a14*a08);
  if (res[23]!=0) res[23][2]=a08;
  a08=arg[14]? arg[14][12] : 0;
  a08=(a08-a09);
  a22=(a07*a08);
  a21=arg[14]? arg[14][13] : 0;
  a21=(a21-a13);
  a16=(a11*a21);
  a12=arg[14]? arg[14][14] : 0;
  a12=(a12-a17);
  a23=(a15*a12);
  a16=(a16+a23);
  a22=(a22+a16);
  a22=(a03*a22);
  if (res[24]!=0) res[24][0]=a22;
  a22=(a01*a08);
  a16=(a04*a21);
  a23=(a05*a12);
  a16=(a16+a23);
  a22=(a22+a16);
  a22=(a10*a22);
  if (res[24]!=0) res[24][1]=a22;
  a08=(a18*a08);
  a21=(a19*a21);
  a12=(a20*a12);
  a21=(a21+a12);
  a08=(a08+a21);
  a08=(a14*a08);
  if (res[24]!=0) res[24][2]=a08;
  a08=arg[15]? arg[15][12] : 0;
  a08=(a08-a09);
  a09=(a07*a08);
  a21=arg[15]? arg[15][13] : 0;
  a21=(a21-a13);
  a13=(a11*a21);
  a12=arg[15]? arg[15][14] : 0;
  a12=(a12-a17);
  a17=(a15*a12);
  a13=(a13+a17);
  a09=(a09+a13);
  a09=(a03*a09);
  a13=1.4999999999999999e-02;
  a09=(a09+a13);
  if (res[25]!=0) res[25][0]=a09;
  a09=(a01*a08);
  a13=(a04*a21);
  a17=(a05*a12);
  a13=(a13+a17);
  a09=(a09+a13);
  a09=(a10*a09);
  a13=-5.0000000000000003e-02;
  a09=(a09+a13);
  if (res[25]!=0) res[25][1]=a09;
  a08=(a18*a08);
  a21=(a19*a21);
  a12=(a20*a12);
  a21=(a21+a12);
  a08=(a08+a21);
  a08=(a14*a08);
  if (res[25]!=0) res[25][2]=a08;
  a08=arg[5]? arg[5][0] : 0;
  a21=arg[10]? arg[10][12] : 0;
  a12=arg[5]? arg[5][12] : 0;
  a21=(a21-a12);
  a09=(a08*a21);
  a13=arg[5]? arg[5][1] : 0;
  a17=arg[10]? arg[10][13] : 0;
  a22=arg[5]? arg[5][13] : 0;
  a17=(a17-a22);
  a16=(a13*a17);
  a23=arg[5]? arg[5][2] : 0;
  a24=arg[10]? arg[10][14] : 0;
  a25=arg[5]? arg[5][14] : 0;
  a24=(a24-a25);
  a26=(a23*a24);
  a16=(a16+a26);
  a09=(a09+a16);
  a09=(a03*a09);
  if (res[26]!=0) res[26][0]=a09;
  a09=(a06*a21);
  a16=(a00*a17);
  a26=(a02*a24);
  a16=(a16+a26);
  a09=(a09+a16);
  a09=(a10*a09);
  if (res[26]!=0) res[26][1]=a09;
  a09=arg[5]? arg[5][8] : 0;
  a21=(a09*a21);
  a16=arg[5]? arg[5][9] : 0;
  a17=(a16*a17);
  a26=arg[5]? arg[5][10] : 0;
  a24=(a26*a24);
  a17=(a17+a24);
  a21=(a21+a17);
  a21=(a14*a21);
  if (res[26]!=0) res[26][2]=a21;
  a21=arg[6]? arg[6][12] : 0;
  a21=(a21-a12);
  a17=(a08*a21);
  a24=arg[6]? arg[6][13] : 0;
  a24=(a24-a22);
  a27=(a13*a24);
  a28=arg[6]? arg[6][14] : 0;
  a28=(a28-a25);
  a29=(a23*a28);
  a27=(a27+a29);
  a17=(a17+a27);
  a17=(a03*a17);
  if (res[27]!=0) res[27][0]=a17;
  a17=(a06*a21);
  a27=(a00*a24);
  a29=(a02*a28);
  a27=(a27+a29);
  a17=(a17+a27);
  a17=(a10*a17);
  if (res[27]!=0) res[27][1]=a17;
  a21=(a09*a21);
  a24=(a16*a24);
  a28=(a26*a28);
  a24=(a24+a28);
  a21=(a21+a24);
  a21=(a14*a21);
  if (res[27]!=0) res[27][2]=a21;
  a21=arg[7]? arg[7][12] : 0;
  a21=(a21-a12);
  a24=(a08*a21);
  a28=arg[7]? arg[7][13] : 0;
  a28=(a28-a22);
  a17=(a13*a28);
  a27=arg[7]? arg[7][14] : 0;
  a27=(a27-a25);
  a29=(a23*a27);
  a17=(a17+a29);
  a24=(a24+a17);
  a24=(a03*a24);
  if (res[28]!=0) res[28][0]=a24;
  a24=(a06*a21);
  a17=(a00*a28);
  a29=(a02*a27);
  a17=(a17+a29);
  a24=(a24+a17);
  a24=(a10*a24);
  if (res[28]!=0) res[28][1]=a24;
  a21=(a09*a21);
  a28=(a16*a28);
  a27=(a26*a27);
  a28=(a28+a27);
  a21=(a21+a28);
  a21=(a14*a21);
  if (res[28]!=0) res[28][2]=a21;
  a21=arg[8]? arg[8][12] : 0;
  a21=(a21-a12);
  a28=(a08*a21);
  a27=arg[8]? arg[8][13] : 0;
  a27=(a27-a22);
  a24=(a13*a27);
  a17=arg[8]? arg[8][14] : 0;
  a17=(a17-a25);
  a29=(a23*a17);
  a24=(a24+a29);
  a28=(a28+a24);
  a28=(a03*a28);
  if (res[29]!=0) res[29][0]=a28;
  a28=(a06*a21);
  a24=(a00*a27);
  a29=(a02*a17);
  a24=(a24+a29);
  a28=(a28+a24);
  a28=(a10*a28);
  if (res[29]!=0) res[29][1]=a28;
  a21=(a09*a21);
  a27=(a16*a27);
  a17=(a26*a17);
  a27=(a27+a17);
  a21=(a21+a27);
  a21=(a14*a21);
  if (res[29]!=0) res[29][2]=a21;
  a21=arg[9]? arg[9][12] : 0;
  a21=(a21-a12);
  a12=(a08*a21);
  a27=arg[9]? arg[9][13] : 0;
  a27=(a27-a22);
  a22=(a13*a27);
  a17=arg[9]? arg[9][14] : 0;
  a17=(a17-a25);
  a25=(a23*a17);
  a22=(a22+a25);
  a12=(a12+a22);
  a03=(a03*a12);
  a12=-1.4999999999999999e-02;
  a03=(a03+a12);
  if (res[30]!=0) res[30][0]=a03;
  a03=(a06*a21);
  a12=(a00*a27);
  a22=(a02*a17);
  a12=(a12+a22);
  a03=(a03+a12);
  a10=(a10*a03);
  a03=5.0000000000000003e-02;
  a10=(a10+a03);
  if (res[30]!=0) res[30][1]=a10;
  a21=(a09*a21);
  a27=(a16*a27);
  a17=(a26*a17);
  a27=(a27+a17);
  a21=(a21+a27);
  a14=(a14*a21);
  if (res[30]!=0) res[30][2]=a14;
  a14=arg[16]? arg[16][4] : 0;
  a21=(a07*a14);
  a27=arg[16]? arg[16][5] : 0;
  a17=(a11*a27);
  a10=arg[16]? arg[16][6] : 0;
  a03=(a15*a10);
  a17=(a17+a03);
  a21=(a21+a17);
  if (res[31]!=0) res[31][0]=a21;
  a21=(a01*a14);
  a17=(a04*a27);
  a03=(a05*a10);
  a17=(a17+a03);
  a21=(a21+a17);
  if (res[31]!=0) res[31][1]=a21;
  a14=(a18*a14);
  a27=(a19*a27);
  a10=(a20*a10);
  a27=(a27+a10);
  a14=(a14+a27);
  if (res[31]!=0) res[31][2]=a14;
  a14=arg[12]? arg[12][4] : 0;
  a27=(a07*a14);
  a10=arg[12]? arg[12][5] : 0;
  a21=(a11*a10);
  a17=arg[12]? arg[12][6] : 0;
  a03=(a15*a17);
  a21=(a21+a03);
  a27=(a27+a21);
  if (res[32]!=0) res[32][0]=a27;
  a27=(a01*a14);
  a21=(a04*a10);
  a03=(a05*a17);
  a21=(a21+a03);
  a27=(a27+a21);
  if (res[32]!=0) res[32][1]=a27;
  a14=(a18*a14);
  a10=(a19*a10);
  a17=(a20*a17);
  a10=(a10+a17);
  a14=(a14+a10);
  if (res[32]!=0) res[32][2]=a14;
  a14=arg[13]? arg[13][4] : 0;
  a10=(a07*a14);
  a17=arg[13]? arg[13][5] : 0;
  a27=(a11*a17);
  a21=arg[13]? arg[13][6] : 0;
  a03=(a15*a21);
  a27=(a27+a03);
  a10=(a10+a27);
  if (res[33]!=0) res[33][0]=a10;
  a10=(a01*a14);
  a27=(a04*a17);
  a03=(a05*a21);
  a27=(a27+a03);
  a10=(a10+a27);
  if (res[33]!=0) res[33][1]=a10;
  a14=(a18*a14);
  a17=(a19*a17);
  a21=(a20*a21);
  a17=(a17+a21);
  a14=(a14+a17);
  if (res[33]!=0) res[33][2]=a14;
  a14=arg[14]? arg[14][4] : 0;
  a17=(a07*a14);
  a21=arg[14]? arg[14][5] : 0;
  a10=(a11*a21);
  a27=arg[14]? arg[14][6] : 0;
  a03=(a15*a27);
  a10=(a10+a03);
  a17=(a17+a10);
  if (res[34]!=0) res[34][0]=a17;
  a17=(a01*a14);
  a10=(a04*a21);
  a03=(a05*a27);
  a10=(a10+a03);
  a17=(a17+a10);
  if (res[34]!=0) res[34][1]=a17;
  a14=(a18*a14);
  a21=(a19*a21);
  a27=(a20*a27);
  a21=(a21+a27);
  a14=(a14+a21);
  if (res[34]!=0) res[34][2]=a14;
  a14=arg[15]? arg[15][4] : 0;
  a07=(a07*a14);
  a21=arg[15]? arg[15][5] : 0;
  a11=(a11*a21);
  a27=arg[15]? arg[15][6] : 0;
  a15=(a15*a27);
  a11=(a11+a15);
  a07=(a07+a11);
  if (res[35]!=0) res[35][0]=a07;
  a01=(a01*a14);
  a04=(a04*a21);
  a05=(a05*a27);
  a04=(a04+a05);
  a01=(a01+a04);
  if (res[35]!=0) res[35][1]=a01;
  a18=(a18*a14);
  a19=(a19*a21);
  a20=(a20*a27);
  a19=(a19+a20);
  a18=(a18+a19);
  if (res[35]!=0) res[35][2]=a18;
  a18=arg[10]? arg[10][4] : 0;
  a19=(a08*a18);
  a20=arg[10]? arg[10][5] : 0;
  a27=(a13*a20);
  a21=arg[10]? arg[10][6] : 0;
  a14=(a23*a21);
  a27=(a27+a14);
  a19=(a19+a27);
  if (res[36]!=0) res[36][0]=a19;
  a19=(a06*a18);
  a27=(a00*a20);
  a14=(a02*a21);
  a27=(a27+a14);
  a19=(a19+a27);
  if (res[36]!=0) res[36][1]=a19;
  a18=(a09*a18);
  a20=(a16*a20);
  a21=(a26*a21);
  a20=(a20+a21);
  a18=(a18+a20);
  if (res[36]!=0) res[36][2]=a18;
  a18=arg[6]? arg[6][4] : 0;
  a20=(a08*a18);
  a21=arg[6]? arg[6][5] : 0;
  a19=(a13*a21);
  a27=arg[6]? arg[6][6] : 0;
  a14=(a23*a27);
  a19=(a19+a14);
  a20=(a20+a19);
  if (res[37]!=0) res[37][0]=a20;
  a20=(a06*a18);
  a19=(a00*a21);
  a14=(a02*a27);
  a19=(a19+a14);
  a20=(a20+a19);
  if (res[37]!=0) res[37][1]=a20;
  a18=(a09*a18);
  a21=(a16*a21);
  a27=(a26*a27);
  a21=(a21+a27);
  a18=(a18+a21);
  if (res[37]!=0) res[37][2]=a18;
  a18=arg[7]? arg[7][4] : 0;
  a21=(a08*a18);
  a27=arg[7]? arg[7][5] : 0;
  a20=(a13*a27);
  a19=arg[7]? arg[7][6] : 0;
  a14=(a23*a19);
  a20=(a20+a14);
  a21=(a21+a20);
  if (res[38]!=0) res[38][0]=a21;
  a21=(a06*a18);
  a20=(a00*a27);
  a14=(a02*a19);
  a20=(a20+a14);
  a21=(a21+a20);
  if (res[38]!=0) res[38][1]=a21;
  a18=(a09*a18);
  a27=(a16*a27);
  a19=(a26*a19);
  a27=(a27+a19);
  a18=(a18+a27);
  if (res[38]!=0) res[38][2]=a18;
  a18=arg[8]? arg[8][4] : 0;
  a27=(a08*a18);
  a19=arg[8]? arg[8][5] : 0;
  a21=(a13*a19);
  a20=arg[8]? arg[8][6] : 0;
  a14=(a23*a20);
  a21=(a21+a14);
  a27=(a27+a21);
  if (res[39]!=0) res[39][0]=a27;
  a27=(a06*a18);
  a21=(a00*a19);
  a14=(a02*a20);
  a21=(a21+a14);
  a27=(a27+a21);
  if (res[39]!=0) res[39][1]=a27;
  a18=(a09*a18);
  a19=(a16*a19);
  a20=(a26*a20);
  a19=(a19+a20);
  a18=(a18+a19);
  if (res[39]!=0) res[39][2]=a18;
  a18=arg[9]? arg[9][4] : 0;
  a08=(a08*a18);
  a19=arg[9]? arg[9][5] : 0;
  a13=(a13*a19);
  a20=arg[9]? arg[9][6] : 0;
  a23=(a23*a20);
  a13=(a13+a23);
  a08=(a08+a13);
  if (res[40]!=0) res[40][0]=a08;
  a06=(a06*a18);
  a00=(a00*a19);
  a02=(a02*a20);
  a00=(a00+a02);
  a06=(a06+a00);
  if (res[40]!=0) res[40][1]=a06;
  a09=(a09*a18);
  a16=(a16*a19);
  a26=(a26*a20);
  a16=(a16+a26);
  a09=(a09+a16);
  if (res[40]!=0) res[40][2]=a09;
  return 0;
}

CASADI_SYMBOL_EXPORT int param_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int param_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int param_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void param_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int param_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void param_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void param_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void param_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int param_func_n_in(void) { return 33;}

CASADI_SYMBOL_EXPORT casadi_int param_func_n_out(void) { return 41;}

CASADI_SYMBOL_EXPORT casadi_real param_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* param_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "BodyHips";
    case 1: return "BodySpineUpper";
    case 2: return "BodyLeftScapula";
    case 3: return "BodyRightScapula";
    case 4: return "BodyHead";
    case 5: return "BodyLeftHandMiddleMetacarpal";
    case 6: return "BodyLeftHandIndexTip";
    case 7: return "BodyLeftHandMiddleTip";
    case 8: return "BodyLeftHandRingTip";
    case 9: return "BodyLeftHandLittleTip";
    case 10: return "BodyLeftHandThumbTip";
    case 11: return "BodyRightHandMiddleMetacarpal";
    case 12: return "BodyRightHandIndexTip";
    case 13: return "BodyRightHandMiddleTip";
    case 14: return "BodyRightHandRingTip";
    case 15: return "BodyRightHandLittleTip";
    case 16: return "BodyRightHandThumbTip";
    case 17: return "BodyLeftArmUpper";
    case 18: return "BodyRightArmUpper";
    case 19: return "BodyLeftArmLower";
    case 20: return "BodyRightArmLower";
    case 21: return "BodyLeftHandMiddleProximal";
    case 22: return "BodyRightHandMiddleProximal";
    case 23: return "BodyLeftUpperLeg";
    case 24: return "BodyLeftLowerLeg";
    case 25: return "BodyLeftFootAnkleTwist";
    case 26: return "BodyRightUpperLeg";
    case 27: return "BodyRightLowerLeg";
    case 28: return "BodyRightFootAnkleTwist";
    case 29: return "BodyLeftFootSubtalar";
    case 30: return "BodyLeftFootBall";
    case 31: return "BodyRightFootSubtalar";
    case 32: return "BodyRightFootBall";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* param_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "root_dir_z";
    case 1: return "root_dir_y";
    case 2: return "root_pos";
    case 3: return "torso_dir";
    case 4: return "shoulder_dir";
    case 5: return "head_front_dir";
    case 6: return "head_up_dir";
    case 7: return "L_upper_arm_dir";
    case 8: return "L_lower_arm_dir";
    case 9: return "R_upper_arm_dir";
    case 10: return "R_lower_arm_dir";
    case 11: return "L_upper_leg_dir";
    case 12: return "L_lower_leg_dir";
    case 13: return "R_upper_leg_dir";
    case 14: return "R_lower_leg_dir";
    case 15: return "L_foot_dir_front";
    case 16: return "R_foot_dir_front";
    case 17: return "L_hand_dir_front";
    case 18: return "L_hand_dir_outside";
    case 19: return "R_hand_dir_front";
    case 20: return "R_hand_dir_outside";
    case 21: return "PosInHand_BodyRightHandThumbTip";
    case 22: return "PosInHand_BodyRightHandIndexTip";
    case 23: return "PosInHand_BodyRightHandMiddleTip";
    case 24: return "PosInHand_BodyRightHandRingTip";
    case 25: return "PosInHand_BodyRightHandLittleTip";
    case 26: return "PosInHand_BodyLeftHandThumbTip";
    case 27: return "PosInHand_BodyLeftHandIndexTip";
    case 28: return "PosInHand_BodyLeftHandMiddleTip";
    case 29: return "PosInHand_BodyLeftHandRingTip";
    case 30: return "PosInHand_BodyLeftHandLittleTip";
    case 31: return "DirInHand_BodyRightHandThumbTip";
    case 32: return "DirInHand_BodyRightHandIndexTip";
    case 33: return "DirInHand_BodyRightHandMiddleTip";
    case 34: return "DirInHand_BodyRightHandRingTip";
    case 35: return "DirInHand_BodyRightHandLittleTip";
    case 36: return "DirInHand_BodyLeftHandThumbTip";
    case 37: return "DirInHand_BodyLeftHandIndexTip";
    case 38: return "DirInHand_BodyLeftHandMiddleTip";
    case 39: return "DirInHand_BodyLeftHandRingTip";
    case 40: return "DirInHand_BodyLeftHandLittleTip";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* param_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    case 10: return casadi_s0;
    case 11: return casadi_s0;
    case 12: return casadi_s0;
    case 13: return casadi_s0;
    case 14: return casadi_s0;
    case 15: return casadi_s0;
    case 16: return casadi_s0;
    case 17: return casadi_s0;
    case 18: return casadi_s0;
    case 19: return casadi_s0;
    case 20: return casadi_s0;
    case 21: return casadi_s0;
    case 22: return casadi_s0;
    case 23: return casadi_s0;
    case 24: return casadi_s0;
    case 25: return casadi_s0;
    case 26: return casadi_s0;
    case 27: return casadi_s0;
    case 28: return casadi_s0;
    case 29: return casadi_s0;
    case 30: return casadi_s0;
    case 31: return casadi_s0;
    case 32: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* param_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s1;
    case 6: return casadi_s1;
    case 7: return casadi_s1;
    case 8: return casadi_s1;
    case 9: return casadi_s1;
    case 10: return casadi_s1;
    case 11: return casadi_s1;
    case 12: return casadi_s1;
    case 13: return casadi_s1;
    case 14: return casadi_s1;
    case 15: return casadi_s1;
    case 16: return casadi_s1;
    case 17: return casadi_s1;
    case 18: return casadi_s1;
    case 19: return casadi_s1;
    case 20: return casadi_s1;
    case 21: return casadi_s1;
    case 22: return casadi_s1;
    case 23: return casadi_s1;
    case 24: return casadi_s1;
    case 25: return casadi_s1;
    case 26: return casadi_s1;
    case 27: return casadi_s1;
    case 28: return casadi_s1;
    case 29: return casadi_s1;
    case 30: return casadi_s1;
    case 31: return casadi_s1;
    case 32: return casadi_s1;
    case 33: return casadi_s1;
    case 34: return casadi_s1;
    case 35: return casadi_s1;
    case 36: return casadi_s1;
    case 37: return casadi_s1;
    case 38: return casadi_s1;
    case 39: return casadi_s1;
    case 40: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int param_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 33;
  if (sz_res) *sz_res = 41;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int param_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 33*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 41*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
