/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) param_func_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 4, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};

/* param_func:(Hips[4x4],LeftUpLeg[4x4],RightUpLeg[4x4],Spine[4x4],LeftArm[4x4],RightArm[4x4],LeftForeArm[4x4],LeftHand[4x4],RightForeArm[4x4],RightHand[4x4],LeftLeg[4x4],LeftFoot[4x4],RightLeg[4x4],RightFoot[4x4],Head[4x4])->(root_dir_z[3],root_dir_y[3],root_pos[3],torso_dir[3],shoulder_dir[3],L_upper_arm_dir[3],L_lower_arm_dir[3],L_upper_leg_dir[3],L_lower_leg_dir[3],L_foot_dir_front[3],L_foot_pos[3],R_upper_arm_dir[3],R_lower_arm_dir[3],R_upper_leg_dir[3],R_lower_leg_dir[3],R_foot_dir_front[3],R_foot_pos[3],L_hand_dir_front[3],L_hand_dir_outside[3],R_hand_dir_front[3],R_hand_dir_outside[3],head_up_dir[3],head_front_dir[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16;
  a00=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[2]? arg[2][12] : 0;
  a01=arg[1]? arg[1][12] : 0;
  a02=(a00-a01);
  a03=casadi_sq(a02);
  a04=arg[2]? arg[2][13] : 0;
  a05=arg[1]? arg[1][13] : 0;
  a06=(a04-a05);
  a07=casadi_sq(a06);
  a03=(a03+a07);
  a07=arg[2]? arg[2][14] : 0;
  a08=arg[1]? arg[1][14] : 0;
  a09=(a07-a08);
  a10=casadi_sq(a09);
  a03=(a03+a10);
  a03=sqrt(a03);
  a02=(a02/a03);
  if (res[1]!=0) res[1][0]=a02;
  a06=(a06/a03);
  if (res[1]!=0) res[1][1]=a06;
  a09=(a09/a03);
  if (res[1]!=0) res[1][2]=a09;
  a09=arg[0]? arg[0][12] : 0;
  if (res[2]!=0) res[2][0]=a09;
  a09=arg[0]? arg[0][13] : 0;
  if (res[2]!=0) res[2][1]=a09;
  a09=arg[0]? arg[0][14] : 0;
  if (res[2]!=0) res[2][2]=a09;
  a09=arg[3]? arg[3][8] : 0;
  if (res[3]!=0) res[3][0]=a09;
  a09=arg[3]? arg[3][9] : 0;
  if (res[3]!=0) res[3][1]=a09;
  a09=arg[3]? arg[3][10] : 0;
  if (res[3]!=0) res[3][2]=a09;
  a09=arg[5]? arg[5][12] : 0;
  a03=arg[4]? arg[4][12] : 0;
  a06=(a09-a03);
  a02=casadi_sq(a06);
  a10=arg[5]? arg[5][13] : 0;
  a11=arg[4]? arg[4][13] : 0;
  a12=(a10-a11);
  a13=casadi_sq(a12);
  a02=(a02+a13);
  a13=arg[5]? arg[5][14] : 0;
  a14=arg[4]? arg[4][14] : 0;
  a15=(a13-a14);
  a16=casadi_sq(a15);
  a02=(a02+a16);
  a02=sqrt(a02);
  a06=(a06/a02);
  if (res[4]!=0) res[4][0]=a06;
  a12=(a12/a02);
  if (res[4]!=0) res[4][1]=a12;
  a15=(a15/a02);
  if (res[4]!=0) res[4][2]=a15;
  a15=arg[6]? arg[6][12] : 0;
  a03=(a15-a03);
  a02=casadi_sq(a03);
  a12=arg[6]? arg[6][13] : 0;
  a11=(a12-a11);
  a06=casadi_sq(a11);
  a02=(a02+a06);
  a06=arg[6]? arg[6][14] : 0;
  a14=(a06-a14);
  a16=casadi_sq(a14);
  a02=(a02+a16);
  a02=sqrt(a02);
  a03=(a03/a02);
  if (res[5]!=0) res[5][0]=a03;
  a11=(a11/a02);
  if (res[5]!=0) res[5][1]=a11;
  a14=(a14/a02);
  if (res[5]!=0) res[5][2]=a14;
  a14=arg[7]? arg[7][12] : 0;
  a14=(a14-a15);
  a15=casadi_sq(a14);
  a02=arg[7]? arg[7][13] : 0;
  a02=(a02-a12);
  a12=casadi_sq(a02);
  a15=(a15+a12);
  a12=arg[7]? arg[7][14] : 0;
  a12=(a12-a06);
  a06=casadi_sq(a12);
  a15=(a15+a06);
  a15=sqrt(a15);
  a14=(a14/a15);
  if (res[6]!=0) res[6][0]=a14;
  a02=(a02/a15);
  if (res[6]!=0) res[6][1]=a02;
  a12=(a12/a15);
  if (res[6]!=0) res[6][2]=a12;
  a12=arg[10]? arg[10][12] : 0;
  a12=(a12-a01);
  a15=casadi_sq(a12);
  a02=arg[10]? arg[10][13] : 0;
  a02=(a02-a05);
  a14=casadi_sq(a02);
  a15=(a15+a14);
  a14=arg[10]? arg[10][14] : 0;
  a14=(a14-a08);
  a06=casadi_sq(a14);
  a15=(a15+a06);
  a15=sqrt(a15);
  a12=(a12/a15);
  if (res[7]!=0) res[7][0]=a12;
  a02=(a02/a15);
  if (res[7]!=0) res[7][1]=a02;
  a14=(a14/a15);
  if (res[7]!=0) res[7][2]=a14;
  a14=arg[11]? arg[11][12] : 0;
  a01=(a14-a01);
  a15=casadi_sq(a01);
  a02=arg[11]? arg[11][13] : 0;
  a05=(a02-a05);
  a12=casadi_sq(a05);
  a15=(a15+a12);
  a12=arg[11]? arg[11][14] : 0;
  a08=(a12-a08);
  a06=casadi_sq(a08);
  a15=(a15+a06);
  a15=sqrt(a15);
  a01=(a01/a15);
  if (res[8]!=0) res[8][0]=a01;
  a05=(a05/a15);
  if (res[8]!=0) res[8][1]=a05;
  a08=(a08/a15);
  if (res[8]!=0) res[8][2]=a08;
  a08=arg[11]? arg[11][0] : 0;
  if (res[9]!=0) res[9][0]=a08;
  a08=arg[11]? arg[11][1] : 0;
  if (res[9]!=0) res[9][1]=a08;
  a08=arg[11]? arg[11][2] : 0;
  if (res[9]!=0) res[9][2]=a08;
  if (res[10]!=0) res[10][0]=a14;
  if (res[10]!=0) res[10][1]=a02;
  if (res[10]!=0) res[10][2]=a12;
  a12=arg[8]? arg[8][12] : 0;
  a09=(a12-a09);
  a02=casadi_sq(a09);
  a14=arg[8]? arg[8][13] : 0;
  a10=(a14-a10);
  a08=casadi_sq(a10);
  a02=(a02+a08);
  a08=arg[8]? arg[8][14] : 0;
  a13=(a08-a13);
  a15=casadi_sq(a13);
  a02=(a02+a15);
  a02=sqrt(a02);
  a09=(a09/a02);
  if (res[11]!=0) res[11][0]=a09;
  a10=(a10/a02);
  if (res[11]!=0) res[11][1]=a10;
  a13=(a13/a02);
  if (res[11]!=0) res[11][2]=a13;
  a13=arg[9]? arg[9][12] : 0;
  a13=(a13-a12);
  a12=casadi_sq(a13);
  a02=arg[9]? arg[9][13] : 0;
  a02=(a02-a14);
  a14=casadi_sq(a02);
  a12=(a12+a14);
  a14=arg[9]? arg[9][14] : 0;
  a14=(a14-a08);
  a08=casadi_sq(a14);
  a12=(a12+a08);
  a12=sqrt(a12);
  a13=(a13/a12);
  if (res[12]!=0) res[12][0]=a13;
  a02=(a02/a12);
  if (res[12]!=0) res[12][1]=a02;
  a14=(a14/a12);
  if (res[12]!=0) res[12][2]=a14;
  a14=arg[12]? arg[12][12] : 0;
  a00=(a14-a00);
  a12=casadi_sq(a00);
  a02=arg[12]? arg[12][13] : 0;
  a04=(a02-a04);
  a13=casadi_sq(a04);
  a12=(a12+a13);
  a13=arg[12]? arg[12][14] : 0;
  a07=(a13-a07);
  a08=casadi_sq(a07);
  a12=(a12+a08);
  a12=sqrt(a12);
  a00=(a00/a12);
  if (res[13]!=0) res[13][0]=a00;
  a04=(a04/a12);
  if (res[13]!=0) res[13][1]=a04;
  a07=(a07/a12);
  if (res[13]!=0) res[13][2]=a07;
  a07=arg[13]? arg[13][12] : 0;
  a14=(a07-a14);
  a12=casadi_sq(a14);
  a04=arg[13]? arg[13][13] : 0;
  a02=(a04-a02);
  a00=casadi_sq(a02);
  a12=(a12+a00);
  a00=arg[13]? arg[13][14] : 0;
  a13=(a00-a13);
  a08=casadi_sq(a13);
  a12=(a12+a08);
  a12=sqrt(a12);
  a14=(a14/a12);
  if (res[14]!=0) res[14][0]=a14;
  a02=(a02/a12);
  if (res[14]!=0) res[14][1]=a02;
  a13=(a13/a12);
  if (res[14]!=0) res[14][2]=a13;
  a13=arg[13]? arg[13][0] : 0;
  if (res[15]!=0) res[15][0]=a13;
  a13=arg[13]? arg[13][1] : 0;
  if (res[15]!=0) res[15][1]=a13;
  a13=arg[13]? arg[13][2] : 0;
  if (res[15]!=0) res[15][2]=a13;
  if (res[16]!=0) res[16][0]=a07;
  if (res[16]!=0) res[16][1]=a04;
  if (res[16]!=0) res[16][2]=a00;
  a00=arg[7]? arg[7][4] : 0;
  if (res[17]!=0) res[17][0]=a00;
  a00=arg[7]? arg[7][5] : 0;
  if (res[17]!=0) res[17][1]=a00;
  a00=arg[7]? arg[7][6] : 0;
  if (res[17]!=0) res[17][2]=a00;
  a00=arg[7]? arg[7][0] : 0;
  a00=(-a00);
  if (res[18]!=0) res[18][0]=a00;
  a00=arg[7]? arg[7][1] : 0;
  a00=(-a00);
  if (res[18]!=0) res[18][1]=a00;
  a00=arg[7]? arg[7][2] : 0;
  a00=(-a00);
  if (res[18]!=0) res[18][2]=a00;
  a00=arg[9]? arg[9][4] : 0;
  a00=(-a00);
  if (res[19]!=0) res[19][0]=a00;
  a00=arg[9]? arg[9][5] : 0;
  a00=(-a00);
  if (res[19]!=0) res[19][1]=a00;
  a00=arg[9]? arg[9][6] : 0;
  a00=(-a00);
  if (res[19]!=0) res[19][2]=a00;
  a00=arg[9]? arg[9][0] : 0;
  a00=(-a00);
  if (res[20]!=0) res[20][0]=a00;
  a00=arg[9]? arg[9][1] : 0;
  a00=(-a00);
  if (res[20]!=0) res[20][1]=a00;
  a00=arg[9]? arg[9][2] : 0;
  a00=(-a00);
  if (res[20]!=0) res[20][2]=a00;
  a00=arg[14]? arg[14][8] : 0;
  if (res[21]!=0) res[21][0]=a00;
  a00=arg[14]? arg[14][9] : 0;
  if (res[21]!=0) res[21][1]=a00;
  a00=arg[14]? arg[14][10] : 0;
  if (res[21]!=0) res[21][2]=a00;
  a00=arg[14]? arg[14][0] : 0;
  if (res[22]!=0) res[22][0]=a00;
  a00=arg[14]? arg[14][1] : 0;
  if (res[22]!=0) res[22][1]=a00;
  a00=arg[14]? arg[14][2] : 0;
  if (res[22]!=0) res[22][2]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int param_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int param_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int param_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void param_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int param_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void param_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void param_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void param_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int param_func_n_in(void) { return 15;}

CASADI_SYMBOL_EXPORT casadi_int param_func_n_out(void) { return 23;}

CASADI_SYMBOL_EXPORT casadi_real param_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* param_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "Hips";
    case 1: return "LeftUpLeg";
    case 2: return "RightUpLeg";
    case 3: return "Spine";
    case 4: return "LeftArm";
    case 5: return "RightArm";
    case 6: return "LeftForeArm";
    case 7: return "LeftHand";
    case 8: return "RightForeArm";
    case 9: return "RightHand";
    case 10: return "LeftLeg";
    case 11: return "LeftFoot";
    case 12: return "RightLeg";
    case 13: return "RightFoot";
    case 14: return "Head";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* param_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "root_dir_z";
    case 1: return "root_dir_y";
    case 2: return "root_pos";
    case 3: return "torso_dir";
    case 4: return "shoulder_dir";
    case 5: return "L_upper_arm_dir";
    case 6: return "L_lower_arm_dir";
    case 7: return "L_upper_leg_dir";
    case 8: return "L_lower_leg_dir";
    case 9: return "L_foot_dir_front";
    case 10: return "L_foot_pos";
    case 11: return "R_upper_arm_dir";
    case 12: return "R_lower_arm_dir";
    case 13: return "R_upper_leg_dir";
    case 14: return "R_lower_leg_dir";
    case 15: return "R_foot_dir_front";
    case 16: return "R_foot_pos";
    case 17: return "L_hand_dir_front";
    case 18: return "L_hand_dir_outside";
    case 19: return "R_hand_dir_front";
    case 20: return "R_hand_dir_outside";
    case 21: return "head_up_dir";
    case 22: return "head_front_dir";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* param_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    case 10: return casadi_s0;
    case 11: return casadi_s0;
    case 12: return casadi_s0;
    case 13: return casadi_s0;
    case 14: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* param_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s1;
    case 6: return casadi_s1;
    case 7: return casadi_s1;
    case 8: return casadi_s1;
    case 9: return casadi_s1;
    case 10: return casadi_s1;
    case 11: return casadi_s1;
    case 12: return casadi_s1;
    case 13: return casadi_s1;
    case 14: return casadi_s1;
    case 15: return casadi_s1;
    case 16: return casadi_s1;
    case 17: return casadi_s1;
    case 18: return casadi_s1;
    case 19: return casadi_s1;
    case 20: return casadi_s1;
    case 21: return casadi_s1;
    case 22: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int param_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 23;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int param_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 23*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
